<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_asDfQBkUEe-yBLl2X56m4w" name="RegistarOportunidadeVenda" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_asDfQRkUEe-yBLl2X56m4w" name="Registar Oportunidade de Venda">
      <elements xmi:type="process:Lane" xmi:id="_asDfQhkUEe-yBLl2X56m4w" name="Gestor da Unidade de Negócio" actor="_mM8vECQWEe-tg7y1lld14w">
        <elements xmi:type="process:CallActivity" xmi:id="_h6iLkCP-Ee-Mys7s4UWPsg" name="Atribui o gestor de venda" outgoing="_vXEpMCP-Ee-Mys7s4UWPsg" incoming="_r_20wCQJEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_h6kn0CP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_h6kAwCP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_h6kn0SP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_h6kn1CP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_h6kn1SP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_h6kn1iP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_h6kn2CP-Ee-Mys7s4UWPsg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_h6kn1yP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_vb8IkC5mEe-f19IC3dmO7g" subprocessSource="oportunidadeDeVenda" processTarget="_ldqOcC5OEe-f19IC3dmO7g"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_h6kn0iP-Ee-Mys7s4UWPsg" name="Atribuição do Gestor de Venda" content="Atribuição do Gestor de Venda" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_h6kn0yP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartMessageEvent" xmi:id="_2mQBICQIEe-tg7y1lld14w" name="surge uma lead" outgoing="_r_20wCQJEe-tg7y1lld14w" event="send_new_lead" incomingMessag="_plr1sC78Ee-URJPyOm92Yg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2mQoMSQIEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2mQoMCQIEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2mQoMiQIEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <messageContent xmi:type="expression:Operation" xmi:id="_NUPDcC5mEe-f19IC3dmO7g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_NUPDcS5mEe-f19IC3dmO7g" name="novaOportunidadeDeVenda" content="novaOportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mc2ZUC74Ee-URJPyOm92Yg" name="novaOportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_NUPDcy5mEe-f19IC3dmO7g" name="novaOportunidadeDeVenda" content="novaOportunidadeDeVenda" type="MESSAGE_ID_TYPE"/>
            <operator xmi:type="expression:Operator" xmi:id="_NUPDdC5mEe-f19IC3dmO7g" type="ASSIGNMENT"/>
          </messageContent>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Um81oCP-Ee-Mys7s4UWPsg" name="Gestor de  Oportunidade de Venda" actor="_pHtQACQWEe-tg7y1lld14w">
        <elements xmi:type="process:XORGateway" xmi:id="_rvFO0CP-Ee-Mys7s4UWPsg" name="Existe ficha de cliente?" outgoing="_24OGcCP-Ee-Mys7s4UWPsg _AgQ-wCP_Ee-Mys7s4UWPsg" incoming="_vXEpMCP-Ee-Mys7s4UWPsg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rvFO0iP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rvFO0SP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rvFO0yP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_z89PMCP-Ee-Mys7s4UWPsg" name="Regista a lead no CRM" outgoing="_RgPt8CP_Ee-Mys7s4UWPsg" incoming="_24OGcCP-Ee-Mys7s4UWPsg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z89PMiP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z89PMSP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z89PMyP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z89PNiP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z89PNyP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z89POCP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z89POiP-Ee-Mys7s4UWPsg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z89POSP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_z89PNCP-Ee-Mys7s4UWPsg" name="Regista a lead no CRM" content="Regista a lead no CRM" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_z89PNSP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_8zmfwCP-Ee-Mys7s4UWPsg" name="Abrir ficha de cliente" outgoing="_JqvxUCP_Ee-Mys7s4UWPsg" incoming="_AgQ-wCP_Ee-Mys7s4UWPsg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8znG0SP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8znG0CP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8znG0iP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8znG1SP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8znG1iP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8znG1yP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8znG2SP-Ee-Mys7s4UWPsg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8znG2CP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_8znG0yP-Ee-Mys7s4UWPsg" name="Abrir Ficha de Cliente" content="Abrir Ficha de Cliente" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_8znG1CP-Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_GUPIgCP_Ee-Mys7s4UWPsg" name="Regista a lead no CRM 2" outgoing="_VSX7wSP_Ee-Mys7s4UWPsg" incoming="_JqvxUCP_Ee-Mys7s4UWPsg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GUPvkSP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GUPvkCP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GUPvkiP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GUPvlSP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GUPvliP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GUPvlyP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GUPvmSP_Ee-Mys7s4UWPsg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GUPvmCP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_GUPvkyP_Ee-Mys7s4UWPsg" name="Regista a lead no CRM" content="Regista a lead no CRM" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_GUPvlCP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_TqhNICP_Ee-Mys7s4UWPsg" name="Acrementa a numeração das leads" outgoing="_b2YbUCP_Ee-Mys7s4UWPsg" incoming="_RgPt8CP_Ee-Mys7s4UWPsg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_O-gxAiP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_O-gxASP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_O-gxAyP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_O-gxBCP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_O-gxBSP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_O-gxBiP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_O-gxCCP_Ee-Mys7s4UWPsg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_O-gxByP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_VSXUsCP_Ee-Mys7s4UWPsg" name="Acrementa a numeração das leads 2" outgoing="_bJrGVCP_Ee-Mys7s4UWPsg" incoming="_VSX7wSP_Ee-Mys7s4UWPsg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VSXUsiP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VSXUsSP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VSXUsyP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VSXUtCP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VSXUtSP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VSXUtiP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VSXUuCP_Ee-Mys7s4UWPsg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VSXUtyP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_bJqfQCP_Ee-Mys7s4UWPsg" name="lead registada no CRM 2" incoming="_bJrGVCP_Ee-Mys7s4UWPsg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bJqfQiP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bJqfQSP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bJqfQyP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_b2X0QCP_Ee-Mys7s4UWPsg" name="lead registada no CRM" incoming="_b2YbUCP_Ee-Mys7s4UWPsg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b2X0QiP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b2X0QSP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b2X0QyP_Ee-Mys7s4UWPsg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ldqOcC5OEe-f19IC3dmO7g" name="novaOportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ldqOcS5OEe-f19IC3dmO7g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_asDfVBkUEe-yBLl2X56m4w" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_sv8tUC5vEe-f19IC3dmO7g" name="processForm" content="72d18588-8958-4553-8780-354eca6afaad" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_asDfVhkUEe-yBLl2X56m4w" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_asDfVxkUEe-yBLl2X56m4w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vXEpMCP-Ee-Mys7s4UWPsg" target="_rvFO0CP-Ee-Mys7s4UWPsg" source="_h6iLkCP-Ee-Mys7s4UWPsg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vXEpMSP-Ee-Mys7s4UWPsg"/>
        <condition xmi:type="expression:Expression" xmi:id="_vXFQQCP-Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_24OGcCP-Ee-Mys7s4UWPsg" name="sim" target="_z89PMCP-Ee-Mys7s4UWPsg" source="_rvFO0CP-Ee-Mys7s4UWPsg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_24OGcSP-Ee-Mys7s4UWPsg"/>
        <condition xmi:type="expression:Expression" xmi:id="_24OGciP-Ee-Mys7s4UWPsg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AgQ-wCP_Ee-Mys7s4UWPsg" name="não" target="_8zmfwCP-Ee-Mys7s4UWPsg" source="_rvFO0CP-Ee-Mys7s4UWPsg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AgQ-wSP_Ee-Mys7s4UWPsg"/>
        <condition xmi:type="expression:Expression" xmi:id="_AgQ-wiP_Ee-Mys7s4UWPsg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JqvxUCP_Ee-Mys7s4UWPsg" target="_GUPIgCP_Ee-Mys7s4UWPsg" source="_8zmfwCP-Ee-Mys7s4UWPsg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JqvxUSP_Ee-Mys7s4UWPsg"/>
        <condition xmi:type="expression:Expression" xmi:id="_JqvxUiP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RgPt8CP_Ee-Mys7s4UWPsg" target="_TqhNICP_Ee-Mys7s4UWPsg" source="_z89PMCP-Ee-Mys7s4UWPsg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RgPt8SP_Ee-Mys7s4UWPsg"/>
        <condition xmi:type="expression:Expression" xmi:id="_RgPt8iP_Ee-Mys7s4UWPsg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VSX7wSP_Ee-Mys7s4UWPsg" target="_VSXUsCP_Ee-Mys7s4UWPsg" source="_GUPIgCP_Ee-Mys7s4UWPsg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VSX7wiP_Ee-Mys7s4UWPsg"/>
        <condition xmi:type="expression:Expression" xmi:id="_VSX7wyP_Ee-Mys7s4UWPsg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bJrGVCP_Ee-Mys7s4UWPsg" target="_bJqfQCP_Ee-Mys7s4UWPsg" source="_VSXUsCP_Ee-Mys7s4UWPsg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bJrGVSP_Ee-Mys7s4UWPsg"/>
        <condition xmi:type="expression:Expression" xmi:id="_bJrGViP_Ee-Mys7s4UWPsg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_b2YbUCP_Ee-Mys7s4UWPsg" target="_b2X0QCP_Ee-Mys7s4UWPsg" source="_TqhNICP_Ee-Mys7s4UWPsg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_b2YbUSP_Ee-Mys7s4UWPsg"/>
        <condition xmi:type="expression:Expression" xmi:id="_b2YbUiP_Ee-Mys7s4UWPsg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r_20wCQJEe-tg7y1lld14w" target="_h6iLkCP-Ee-Mys7s4UWPsg" source="_2mQBICQIEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r_20wSQJEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_r_20wiQJEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_mM8vECQWEe-tg7y1lld14w" name="Gestor da Unidade de Negócio" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_pHtQACQWEe-tg7y1lld14w" name="Gestor de Oportunidade de Venda"/>
      <contract xmi:type="process:Contract" xmi:id="_asDfXBkUEe-yBLl2X56m4w"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_asDfXRkUEe-yBLl2X56m4w">
        <name xmi:type="expression:Expression" xmi:id="_asDfXhkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_asDfXxkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_asDfYBkUEe-yBLl2X56m4w">
        <name xmi:type="expression:Expression" xmi:id="_asDfYRkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_asDfYhkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_asDfYxkUEe-yBLl2X56m4w">
        <name xmi:type="expression:Expression" xmi:id="_asDfZBkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_asDfZRkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_asDfZhkUEe-yBLl2X56m4w">
        <name xmi:type="expression:Expression" xmi:id="_asDfZxkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_asDfaBkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_asDfaRkUEe-yBLl2X56m4w">
        <name xmi:type="expression:Expression" xmi:id="_asDfahkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_asDfaxkUEe-yBLl2X56m4w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_-AAWkCQAEe-Mys7s4UWPsg" name="Origem Interna">
      <elements xmi:type="process:StartEvent" xmi:id="_YstbACQHEe-tg7y1lld14w" name="surge uma lead" outgoing="_r_hIcCQHEe-tg7y1lld14w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_YsuCESQHEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_YsuCECQHEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_YsuCEiQHEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_e3XFwCQPEe-tg7y1lld14w" name="Envia a lead para o procedimento de venda" outgoing="_1R1y8CQIEe-tg7y1lld14w" incoming="_r_hIcCQHEe-tg7y1lld14w" actor="_pTl0ECQPEe-tg7y1lld14w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_r_fTQSQHEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_r_fTQCQHEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_r_fTQiQHEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_G0nSMC72Ee-URJPyOm92Yg">
          <leftOperand xmi:type="expression:Expression" xmi:id="_G0nSMS72Ee-URJPyOm92Yg" name="novaOportunidadeDeVenda" content="novaOportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidaDeVenda">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0nSMi72Ee-URJPyOm92Yg" name="novaOportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_G0nSMy72Ee-URJPyOm92Yg" name="novaOportunidadeDeVendaInput.unidade_negocio" content="novaOportunidadeDeVendaInput?.unidade_negocio" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_G0nSNC72Ee-URJPyOm92Yg" name="novaOportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_G0nSNS72Ee-URJPyOm92Yg" type="JAVA_METHOD" expression="setUnidade_negocio">
            <inputTypes>java.lang.String</inputTypes>
          </operator>
        </operations>
        <operations xmi:type="expression:Operation" xmi:id="_G0nSNi72Ee-URJPyOm92Yg">
          <leftOperand xmi:type="expression:Expression" xmi:id="_G0nSNy72Ee-URJPyOm92Yg" name="novaOportunidadeDeVenda" content="novaOportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidaDeVenda">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G0nSOC72Ee-URJPyOm92Yg" name="novaOportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_G0nSOS72Ee-URJPyOm92Yg" name="novaOportunidadeDeVendaInput.cliente" content="novaOportunidadeDeVendaInput?.cliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_G0nSOi72Ee-URJPyOm92Yg" name="novaOportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_G0nSOy72Ee-URJPyOm92Yg" type="JAVA_METHOD" expression="setCliente">
            <inputTypes>java.lang.String</inputTypes>
          </operator>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_r_fTQyQHEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_r_fTRCQHEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_r_fTRSQHEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_r_fTRyQHEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_r_fTRiQHEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_e3Xs2SQPEe-tg7y1lld14w">
          <targetForm xmi:type="expression:Expression" xmi:id="_e3Xs2iQPEe-tg7y1lld14w" name="novaOVForm" content="094e63c7-3de4-4b8b-abc6-54908b2fad42" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_e3Xs2CQPEe-tg7y1lld14w">
          <inputs xmi:type="process:ContractInput" xmi:id="_G0mEEC72Ee-URJPyOm92Yg" name="novaOportunidadeDeVendaInput" type="COMPLEX" dataReference="novaOportunidadeDeVenda" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_G0mEES72Ee-URJPyOm92Yg" name="unidade_negocio" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_G0mEEi72Ee-URJPyOm92Yg" name="cliente" createMode="false"/>
          </inputs>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_e3Xs2yQPEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndMessageEvent" xmi:id="_cVc2EC75Ee-URJPyOm92Yg" name="envia a lead" incoming="_1R1y8CQIEe-tg7y1lld14w" outgoingMessages="_plr1sC78Ee-URJPyOm92Yg">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_08em8iQIEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_08em8SQIEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_08em8yQIEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        <events xmi:type="process:Message" xmi:id="_k07fICQJEe-tg7y1lld14w" name="send_new_lead">
          <correlation xmi:type="process:Correlation" xmi:id="_k07fISQJEe-tg7y1lld14w">
            <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_k07fIiQJEe-tg7y1lld14w"/>
          </correlation>
          <targetProcessExpression xmi:type="expression:Expression" xmi:id="_ployYC78Ee-URJPyOm92Yg" name="Registar Oportunidade de Venda" content="Registar Oportunidade de Venda"/>
          <targetElementExpression xmi:type="expression:Expression" xmi:id="_plqAgC78Ee-URJPyOm92Yg" name="surge uma lead" content="surge uma lead"/>
          <messageContent xmi:type="expression:TableExpression" xmi:id="_k07fJSQJEe-tg7y1lld14w">
            <expressions xmi:type="expression:ListExpression" xmi:id="_KJ_VAC5mEe-f19IC3dmO7g">
              <expressions xmi:type="expression:Expression" xmi:id="_KJ_VAS5mEe-f19IC3dmO7g" name="novaOportunidadeDeVenda" content="novaOportunidadeDeVenda" returnTypeFixed="true"/>
              <expressions xmi:type="expression:Expression" xmi:id="_KJ_VAi5mEe-f19IC3dmO7g" name="novaOportunidadeVenda.get" content="novaOportunidadeDeVenda" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_796HAC74Ee-URJPyOm92Yg" name="novaOportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
              </expressions>
            </expressions>
          </messageContent>
        </events>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_SDBUUC5GEe-f19IC3dmO7g" name="novaOportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda">
        <defaultValue xmi:type="expression:Expression" xmi:id="_SDBUUS5GEe-f19IC3dmO7g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_-IhZYCQAEe-Mys7s4UWPsg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_4urCACQPEe-tg7y1lld14w" name="processForm" content="72d18588-8958-4553-8780-354eca6afaad" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_-IhZYiQAEe-Mys7s4UWPsg" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_-IhZYyQAEe-Mys7s4UWPsg" name="sendNewLeadForm" content="b2c15f95-6778-41c1-9e60-e3c9f35a7b41" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r_hIcCQHEe-tg7y1lld14w" target="_e3XFwCQPEe-tg7y1lld14w" source="_YstbACQHEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r_hIcSQHEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_r_hIciQHEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1R1y8CQIEe-tg7y1lld14w" target="_cVc2EC75Ee-URJPyOm92Yg" source="_e3XFwCQPEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1R1y8SQIEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_1R1y8iQIEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_pTl0ECQPEe-tg7y1lld14w" name="OrigemInterna actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_-IhZZCQAEe-Mys7s4UWPsg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_-IgyUCQAEe-Mys7s4UWPsg">
        <name xmi:type="expression:Expression" xmi:id="_-IgyUSQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_-IgyUiQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_-IgyUyQAEe-Mys7s4UWPsg">
        <name xmi:type="expression:Expression" xmi:id="_-IgyVCQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_-IgyVSQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_-IgyViQAEe-Mys7s4UWPsg">
        <name xmi:type="expression:Expression" xmi:id="_-IgyVyQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_-IgyWCQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_-IgyWSQAEe-Mys7s4UWPsg">
        <name xmi:type="expression:Expression" xmi:id="_-IgyWiQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_-IgyWyQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_-IgyXCQAEe-Mys7s4UWPsg">
        <name xmi:type="expression:Expression" xmi:id="_-IgyXSQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_-IgyXiQAEe-Mys7s4UWPsg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_DTbo8CQKEe-tg7y1lld14w" name="Atribuição do Gestor de Venda">
      <elements xmi:type="process:Lane" xmi:id="_LtjVkCQKEe-tg7y1lld14w" name="Gestor da Unidade de Negócio" actor="_v92ocCQWEe-tg7y1lld14w">
        <elements xmi:type="process:StartEvent" xmi:id="_QG0b4CQKEe-tg7y1lld14w" name="oportunidade venda sem tipo associado" outgoing="_YioKkyQKEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QG0b4iQKEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QG0b4SQKEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QG0b4yQKEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Y_HSQCQKEe-tg7y1lld14w" name="Associa a lead ao respetivo tipo" outgoing="_b-kF9iQKEe-tg7y1lld14w" incoming="_YioKkyQKEe-tg7y1lld14w" actor="_v92ocCQWEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YinjgiQKEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YinjgSQKEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YinjgyQKEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_rreAQC5pEe-f19IC3dmO7g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rreAQS5pEe-f19IC3dmO7g" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_sZ4lcC5pEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rreAQi5pEe-f19IC3dmO7g" name="newScript()" content="String unidadeDeNegocioText = &quot;&quot;;&#xD;&#xA;switch (unidadeDeNegocio) {&#xD;&#xA;&#x9;case &quot;Venda de Produtos&quot;:&#xD;&#xA;&#x9;&#x9;unidadeDeNegocioText=unidadeDeNegocio&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;&#x9;case &quot;Venda de Soluções&quot;:&#xD;&#xA;&#x9;&#x9;unidadeDeNegocioText=unidadeDeNegocio&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;&#x9;case &quot;Venda de Contratos&quot;:&#xD;&#xA;&#x9;&#x9;unidadeDeNegocioText=unidadeDeNegocio&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;&#x9;default:&#xD;&#xA;&#x9;&#x9;unidadeDeNegocioText=&quot;&quot;&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;}&#xD;&#xA;oportunidadeDeVenda.unidade_negocio=unidadeDeNegocioText" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2z6pcC5rEe-f19IC3dmO7g" name="unidadeDeNegocio">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_2z6pcS5rEe-f19IC3dmO7g"/>
              </referencedElements>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2z6pci5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rreAQy5pEe-f19IC3dmO7g" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_YinjhCQKEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_YinjhSQKEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_YinjhiQKEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_YinjiCQKEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_YinjhyQKEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Y_H5WSQKEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_S5vLQCQREe-tg7y1lld14w" name="associarTipoToLeadForm" content="93b7823c-4ac5-4fd9-b97b-259fcb4a0f57" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Y_H5WCQKEe-tg7y1lld14w">
            <inputs xmi:type="process:ContractInput" xmi:id="_L0XhQC5oEe-f19IC3dmO7g" name="unidadeDeNegocio">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_L0XhQS5oEe-f19IC3dmO7g"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Y_H5WyQKEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_cnXyYCQKEe-tg7y1lld14w" name="a lead está associada a uma entidade cliente?" outgoing="_UwH3YSQMEe-tg7y1lld14w _dNRC0iQMEe-tg7y1lld14w" incoming="_b-kF9iQKEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b-kF8CQKEe-tg7y1lld14w" name="displayName()" content="if (oportunidadeDeVenda.cliente != null)&#xD;&#xA;&#x9;return true&#xD;&#xA;return false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_T5EQIC5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
          </dynamicLabel>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b-je4SQKEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b-kF8SQKEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_UwGpQCQMEe-tg7y1lld14w" name="Atribui o respetivo gestor de cliente como gestor de OV" outgoing="_ZoTuVCQMEe-tg7y1lld14w" incoming="_UwH3YSQMEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UwHQUSQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UwHQUCQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UwHQUiQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_LkMsYC5qEe-f19IC3dmO7g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_LkMsYS5qEe-f19IC3dmO7g" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_L7jccC5qEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_LkMsYi5qEe-f19IC3dmO7g" name="newScript()" content="oportunidadeDeVenda.gestor_ov = &quot;Gestor &quot; + oportunidadeDeVenda.cliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_y9m7sC5qEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_LkMsYy5qEe-f19IC3dmO7g" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UwHQUyQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UwHQVCQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UwHQVSQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UwHQVyQMEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UwHQViQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_ZoTHQCQMEe-tg7y1lld14w" name="Gestor de Venda Atribuído" incoming="_ZoTuVCQMEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZoTHQiQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZoTHQSQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZoTHQyQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_wdHi4CQMEe-tg7y1lld14w" name="especifica de forma clara a unidade de negócio?" outgoing="_ih0FoyQMEe-tg7y1lld14w _m3az8CQMEe-tg7y1lld14w" incoming="_dNRC0iQMEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dNQbwiQMEe-tg7y1lld14w" name="displayName()" content="if(oportunidadeDeVenda.unidade_negocio != null &amp;&amp; oportunidadeDeVenda.unidade_negocio != &quot;&quot;)&#xD;&#xA;&#x9;return true&#xD;&#xA;return false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_idY1MC5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
          </dynamicLabel>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dNQbwSQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dNQbwyQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_mAw4wCQMEe-tg7y1lld14w" name="Atribui o respetivo gestor de OV" outgoing="_7dk_pyQMEe-tg7y1lld14w" incoming="_ih0FoyQMEe-tg7y1lld14w _uTPsUCQMEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ihzekiQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ihzekSQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ihzekyQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_CFM7AC5tEe-f19IC3dmO7g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_CFM7AS5tEe-f19IC3dmO7g" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_CdQ1sC5tEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_CFM7Ai5tEe-f19IC3dmO7g" name="newScript()" content="oportunidadeDeVenda.gestor_ov = gestor_ov" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KJOb0C5tEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
              <referencedElements xmi:type="process:ContractInput" xmi:id="_KJOb0S5tEe-f19IC3dmO7g" name="gestor_ov">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_KJOb0i5tEe-f19IC3dmO7g"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_CFM7Ay5tEe-f19IC3dmO7g" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ihzelCQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ihzelSQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ihzeliQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ihzemCQMEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ihzelyQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mAxf2SQMEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Wgwn8C5nEe-f19IC3dmO7g" name="atribuirGestorOVForm" content="695edb7e-b3cb-49db-8194-511cda800c56" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mAxf2CQMEe-tg7y1lld14w">
            <inputs xmi:type="process:ContractInput" xmi:id="_IzB6YC5sEe-f19IC3dmO7g" name="gestor_ov">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_IzChcC5sEe-f19IC3dmO7g"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mAxf2yQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_7dkYkCQMEe-tg7y1lld14w" name="Gestor de Venda Atribuído 2" incoming="_7dk_pyQMEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7dk_oSQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7dk_oCQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7dk_oiQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ML-W8CQKEe-tg7y1lld14w" name="Administração" actor="_ymfeoCQWEe-tg7y1lld14w">
        <elements xmi:type="process:Task" xmi:id="_p9_jUCQMEe-tg7y1lld14w" name="Escolhe a unidade de negócio responável" outgoing="_sW8-wCQMEe-tg7y1lld14w" incoming="_m3az8CQMEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_m3aM4iQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_m3aM4SQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_m3aM4yQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_3OTfYC5rEe-f19IC3dmO7g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_3OTfYS5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_3mBb0C5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_3OTfYi5rEe-f19IC3dmO7g" name="newScript()" content="String unidadeDeNegocioText = &quot;&quot;;&#xD;&#xA;switch (unidadeDeNegocio) {&#xD;&#xA;&#x9;case &quot;Venda de Produtos&quot;:&#xD;&#xA;&#x9;&#x9;unidadeDeNegocioText=unidadeDeNegocio&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;&#x9;case &quot;Venda de Soluções&quot;:&#xD;&#xA;&#x9;&#x9;unidadeDeNegocioText=unidadeDeNegocio&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;&#x9;case &quot;Venda de Contratos&quot;:&#xD;&#xA;&#x9;&#x9;unidadeDeNegocioText=unidadeDeNegocio&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;&#x9;default:&#xD;&#xA;&#x9;&#x9;unidadeDeNegocioText=&quot;&quot;&#xD;&#xA;&#x9;&#x9;break;&#xD;&#xA;}&#xD;&#xA;oportunidadeDeVenda.unidade_negocio=unidadeDeNegocioText" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_4n_2MC5rEe-f19IC3dmO7g" name="unidadeDeNegocio">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_4n_2MS5rEe-f19IC3dmO7g"/>
              </referencedElements>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4n_2Mi5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_3OTfYy5rEe-f19IC3dmO7g" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_m3aM5CQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_m3aM5SQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_m3aM5iQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_m3aM6CQMEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_m3aM5yQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_p9_jWiQMEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Wgwn8S5nEe-f19IC3dmO7g" name="associarTipoToLeadForm" content="93b7823c-4ac5-4fd9-b97b-259fcb4a0f57" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_p9_jWSQMEe-tg7y1lld14w">
            <inputs xmi:type="process:ContractInput" xmi:id="_yluxwC5rEe-f19IC3dmO7g" name="unidadeDeNegocio">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_yluxwS5rEe-f19IC3dmO7g"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_p9_jXCQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0lXxsCQMEe-tg7y1lld14w" name="Administração atribui gestor de OV?" outgoing="_uTPsUCQMEe-tg7y1lld14w _2SVp0CQMEe-tg7y1lld14w" incoming="_sW8-wCQMEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sW8XsiQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sW8XsSQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sW8XsyQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4DdCICQMEe-tg7y1lld14w" name="Atribui o respetivo gestor de OV 2" outgoing="_5EDjgiQMEe-tg7y1lld14w" incoming="_2SVp0CQMEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2SUbsiQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2SUbsSQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2SVCwCQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Pa2GcC5tEe-f19IC3dmO7g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Pa2GcS5tEe-f19IC3dmO7g" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PuI14C5tEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Pa2Gci5tEe-f19IC3dmO7g" name="newScript()" content="oportunidadeDeVenda.gestor_ov = gestor_ov" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.OportunidaDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vzg4sC5tEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vzg4sS5tEe-f19IC3dmO7g" name="gestor_ov">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_Vzg4si5tEe-f19IC3dmO7g"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Pa2Gcy5tEe-f19IC3dmO7g" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2SVCwSQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2SVCwiQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2SVCwyQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2SVCxSQMEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2SVCxCQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4DdpOSQMEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Wgwn8i5nEe-f19IC3dmO7g" name="atribuirGestorOVForm" content="695edb7e-b3cb-49db-8194-511cda800c56" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4DdpOCQMEe-tg7y1lld14w">
            <inputs xmi:type="process:ContractInput" xmi:id="_TeDdMC5tEe-f19IC3dmO7g" name="gestor_ov">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_TeDdMS5tEe-f19IC3dmO7g"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4DdpOyQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_5EC8cCQMEe-tg7y1lld14w" name="Gestor de Venda Atribuído 3" incoming="_5EDjgiQMEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5EC8ciQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5EC8cSQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5EC8cyQMEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_-HvOoC5mEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda">
        <defaultValue xmi:type="expression:Expression" xmi:id="_-HvOoS5mEe-f19IC3dmO7g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_DcDZfyQKEe-tg7y1lld14w" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_xx5EkC5sEe-f19IC3dmO7g" name="processForm" content="72d18588-8958-4553-8780-354eca6afaad" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_DcDZgSQKEe-tg7y1lld14w">
        <targetForm xmi:type="expression:Expression" xmi:id="_DcDZgiQKEe-tg7y1lld14w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YioKkyQKEe-tg7y1lld14w" target="_Y_HSQCQKEe-tg7y1lld14w" source="_QG0b4CQKEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YioKlCQKEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_YioKlSQKEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_b-kF9iQKEe-tg7y1lld14w" target="_cnXyYCQKEe-tg7y1lld14w" source="_Y_HSQCQKEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_b-kF9yQKEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_b-kF-CQKEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UwH3YSQMEe-tg7y1lld14w" name="sim" target="_UwGpQCQMEe-tg7y1lld14w" source="_cnXyYCQKEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UwH3YiQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_UwH3YyQMEe-tg7y1lld14w" name="newScript()" content="if (oportunidadeDeVenda.cliente != null &amp;&amp; oportunidadeDeVenda.cliente != &quot;&quot;)&#xD;&#xA;&#x9;return true&#xD;&#xA;return false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_j13EAC5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZoTuVCQMEe-tg7y1lld14w" target="_ZoTHQCQMEe-tg7y1lld14w" source="_UwGpQCQMEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZoTuVSQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZoTuViQMEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dNRC0iQMEe-tg7y1lld14w" name="não" target="_wdHi4CQMEe-tg7y1lld14w" source="_cnXyYCQKEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dNRC0yQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_dNRC1CQMEe-tg7y1lld14w" name="newScript()" content="if (oportunidadeDeVenda.cliente != null &amp;&amp; oportunidadeDeVenda.cliente != &quot;&quot;)&#xD;&#xA;&#x9;return false&#xD;&#xA;return true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_fbXOoC5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ih0FoyQMEe-tg7y1lld14w" name="sim" target="_mAw4wCQMEe-tg7y1lld14w" source="_wdHi4CQMEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ih0FpCQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_ih0FpSQMEe-tg7y1lld14w" name="newScript()" content="if(oportunidadeDeVenda.unidade_negocio != null &amp;&amp; oportunidadeDeVenda.unidade_negocio != &quot;&quot;)&#xD;&#xA;&#x9;return true&#xD;&#xA;return false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mfpJsC5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_m3az8CQMEe-tg7y1lld14w" name="não" target="_p9_jUCQMEe-tg7y1lld14w" source="_wdHi4CQMEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_m3az8SQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_m3az8iQMEe-tg7y1lld14w" name="newScript()" content="if(oportunidadeDeVenda.unidade_negocio != null &amp;&amp; oportunidadeDeVenda.unidade_negocio != &quot;&quot;)&#xD;&#xA;&#x9;return false&#xD;&#xA;return true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_oq0AwC5rEe-f19IC3dmO7g" name="oportunidadeDeVenda" dataType="_asDfdBkUEe-yBLl2X56m4w" className="com.company.model.OportunidaDeVenda"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sW8-wCQMEe-tg7y1lld14w" target="_0lXxsCQMEe-tg7y1lld14w" source="_p9_jUCQMEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sW8-wSQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_sW8-wiQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uTPsUCQMEe-tg7y1lld14w" name="não" target="_mAw4wCQMEe-tg7y1lld14w" source="_0lXxsCQMEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uTPsUSQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_uTPsUiQMEe-tg7y1lld14w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2SVp0CQMEe-tg7y1lld14w" name="sim" target="_4DdCICQMEe-tg7y1lld14w" source="_0lXxsCQMEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2SVp0SQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_2SVp0iQMEe-tg7y1lld14w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5EDjgiQMEe-tg7y1lld14w" target="_5EC8cCQMEe-tg7y1lld14w" source="_4DdCICQMEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5EDjgyQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_5EDjhCQMEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7dk_pyQMEe-tg7y1lld14w" target="_7dkYkCQMEe-tg7y1lld14w" source="_mAw4wCQMEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7dlmsCQMEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_7dlmsSQMEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_v92ocCQWEe-tg7y1lld14w" name="Gestor de Unidade de Negócio"/>
      <actors xmi:type="process:Actor" xmi:id="_ymfeoCQWEe-tg7y1lld14w" name="Administracao"/>
      <contract xmi:type="process:Contract" xmi:id="_DcDZgyQKEe-tg7y1lld14w"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_DcDZcCQKEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_DcDZcSQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_DcDZciQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_DcDZcyQKEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_DcDZdCQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_DcDZdSQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_DcDZdiQKEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_DcDZdyQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_DcDZeCQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_DcDZeSQKEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_DcDZeiQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_DcDZeyQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_DcDZfCQKEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_DcDZfSQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_DcDZfiQKEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_SUlzoCQNEe-tg7y1lld14w" name="Abrir Ficha de Cliente">
      <elements xmi:type="process:Lane" xmi:id="_eGmpICQNEe-tg7y1lld14w" name="Gestor de Oportunidade de Venda" actor="_1GadsCQWEe-tg7y1lld14w">
        <elements xmi:type="process:StartEvent" xmi:id="_hMuskCQNEe-tg7y1lld14w" name="lead sem cliente atribuido" outgoing="_jUo0SyQNEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hMuskiQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hMuskSQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hMvToCQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_j7HlcCQNEe-tg7y1lld14w" name="Verifica a necessidade de recorrer aos serviços de apoio ao negócio" outgoing="_lcBXhyQNEe-tg7y1lld14w" incoming="_jUo0SyQNEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jUo0QSQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jUo0QCQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jUo0QiQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jUo0QyQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jUo0RCQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jUo0RSQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jUo0RyQNEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jUo0RiQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_j7IMgiQNEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Hzv2IC8FEe-lp6-MmZdV-w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_j7IMgSQNEe-tg7y1lld14w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_j7IMhCQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_l8ZgsCQNEe-tg7y1lld14w" name="é necessário recorrer aos serviços de apoio ao negócio?" outgoing="_uo26gyQNEe-tg7y1lld14w _EbdrPCQOEe-tg7y1lld14w" incoming="_lcBXhyQNEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lcBXgSQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lcBXgCQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lcBXgiQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_wbWL0CQNEe-tg7y1lld14w" name="Recorre aos serviços de apoio ao negócio" outgoing="_zay_gCQNEe-tg7y1lld14w" incoming="_uo26gyQNEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uo2TciQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uo2TcSQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uo2TcyQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_uo2TdCQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_uo2TdSQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_uo2TdiQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_uo2TeCQNEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_uo2TdyQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wbWL2iQNEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Hzv2IS8FEe-lp6-MmZdV-w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wbWL2SQNEe-tg7y1lld14w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wbWL3CQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_-iP1ECQNEe-tg7y1lld14w" name="Verificar ficha do cliente" outgoing="_CH9XhyQOEe-tg7y1lld14w" incoming="_7BH3sSQNEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7BHQoiQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7BHQoSQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7BHQoyQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7BHQpCQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7BHQpSQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7BHQpiQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7BHQqCQNEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7BHQpyQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-iQcKSQNEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Hzv2Ii8FEe-lp6-MmZdV-w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-iQcKCQNEe-tg7y1lld14w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-iQcKyQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_CH8wcCQOEe-tg7y1lld14w" name="ficha do cliente aberta 2" incoming="_CH9XhyQOEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CH9XgSQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CH9XgCQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CH9XgiQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_HGPPYCQOEe-tg7y1lld14w" name="Abrir ficha do cliente" outgoing="_JY4ndyQOEe-tg7y1lld14w" incoming="_EbdrPCQOEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EbdrMiQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EbdrMSQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EbdrMyQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EbdrNCQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EbdrNSQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EbdrNiQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EbdrOCQOEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EbdrNyQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HGPPaiQOEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Hzv2Iy8FEe-lp6-MmZdV-w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HGPPaSQOEe-tg7y1lld14w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HGPPbCQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_JY4AYCQOEe-tg7y1lld14w" name="ficha do cliente aberta" incoming="_JY4ndyQOEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JY4ncSQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JY4ncCQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JY4nciQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_eRg4oCQNEe-tg7y1lld14w" name="área comercial" actor="_2OW9MCQWEe-tg7y1lld14w">
        <elements xmi:type="process:Task" xmi:id="_1uL-cCQNEe-tg7y1lld14w" name="Analisa o pedido" outgoing="_21PGGyQNEe-tg7y1lld14w" incoming="_zay_gCQNEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zayYciQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zayYcSQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zayYcyQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zayYdCQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zayYdSQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zayYdiQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zayYeCQNEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zayYdyQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_1uMliSQNEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Hzv2JC8FEe-lp6-MmZdV-w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_1uMliCQNEe-tg7y1lld14w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_1uMliyQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5k5xUCQNEe-tg7y1lld14w" name="Abre a ficha do cliente" outgoing="_7BH3sSQNEe-tg7y1lld14w" incoming="_21PGGyQNEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_21PGESQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_21PGECQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_21PGEiQNEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_21PGEyQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_21PGFCQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_21PGFSQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_21PGFyQNEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_21PGFiQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5k6YaSQNEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Hzv2JS8FEe-lp6-MmZdV-w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5k6YaCQNEe-tg7y1lld14w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5k6YayQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_SUlzsCQNEe-tg7y1lld14w" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_4cYkNi78Ee-URJPyOm92Yg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_SUlzsiQNEe-tg7y1lld14w">
        <targetForm xmi:type="expression:Expression" xmi:id="_SUlzsyQNEe-tg7y1lld14w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jUo0SyQNEe-tg7y1lld14w" target="_j7HlcCQNEe-tg7y1lld14w" source="_hMuskCQNEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jUpbUCQNEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_jUpbUSQNEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lcBXhyQNEe-tg7y1lld14w" target="_l8ZgsCQNEe-tg7y1lld14w" source="_j7HlcCQNEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lcBXiCQNEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_lcBXiSQNEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uo26gyQNEe-tg7y1lld14w" name="sim" target="_wbWL0CQNEe-tg7y1lld14w" source="_l8ZgsCQNEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uo3hkCQNEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_uo3hkSQNEe-tg7y1lld14w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zay_gCQNEe-tg7y1lld14w" target="_1uL-cCQNEe-tg7y1lld14w" source="_wbWL0CQNEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zay_gSQNEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_zay_giQNEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_21PGGyQNEe-tg7y1lld14w" target="_5k5xUCQNEe-tg7y1lld14w" source="_1uL-cCQNEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_21PGHCQNEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_21PGHSQNEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7BH3sSQNEe-tg7y1lld14w" target="_-iP1ECQNEe-tg7y1lld14w" source="_5k5xUCQNEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7BH3siQNEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_7BH3syQNEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CH9XhyQOEe-tg7y1lld14w" target="_CH8wcCQOEe-tg7y1lld14w" source="_-iP1ECQNEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CH9XiCQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_CH9XiSQOEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EbdrPCQOEe-tg7y1lld14w" name="não" target="_HGPPYCQOEe-tg7y1lld14w" source="_l8ZgsCQNEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EbeSQCQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_EbeSQSQOEe-tg7y1lld14w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JY4ndyQOEe-tg7y1lld14w" target="_JY4AYCQOEe-tg7y1lld14w" source="_HGPPYCQOEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JY4neCQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_JY4neSQOEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_1GadsCQWEe-tg7y1lld14w" name="Gestor de Oportunidade de Venda"/>
      <actors xmi:type="process:Actor" xmi:id="_2OW9MCQWEe-tg7y1lld14w" name="Area comercial"/>
      <contract xmi:type="process:Contract" xmi:id="_SUlztCQNEe-tg7y1lld14w"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SUlzoSQNEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_SUlzoiQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SUlzoyQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SUlzpCQNEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_SUlzpSQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SUlzpiQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SUlzpyQNEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_SUlzqCQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SUlzqSQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SUlzqiQNEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_SUlzqyQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SUlzrCQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SUlzrSQNEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_SUlzriQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SUlzryQNEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_ZSmSICQOEe-tg7y1lld14w" name="Regista a lead no CRM">
      <elements xmi:type="process:Lane" xmi:id="_bcXbACQOEe-tg7y1lld14w" name="Gestor de Oportunidade de Venda" actor="_32FwACQWEe-tg7y1lld14w">
        <elements xmi:type="process:StartEvent" xmi:id="_ghQRMCQOEe-tg7y1lld14w" name="lead com cliente já atribuido" outgoing="_jInVCyQOEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ghQRMiQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ghQRMSQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ghQRMyQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_kxxEICQOEe-tg7y1lld14w" name="Verifica se é um novo negócio" outgoing="_mlxYZyQOEe-tg7y1lld14w" incoming="_jInVCyQOEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jInVASQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jInVACQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jInVAiQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jInVAyQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jInVBCQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jInVBSQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jInVByQOEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jInVBiQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_kxxEKiQOEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Ib1J0C8FEe-lp6-MmZdV-w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_kxxEKSQOEe-tg7y1lld14w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_kxxELCQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_m-rnoCQOEe-tg7y1lld14w" name="é um novo negócio?" outgoing="_pPkFISQOEe-tg7y1lld14w _2K8WcCQOEe-tg7y1lld14w" incoming="_mlxYZyQOEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mlxYYSQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mlxYYCQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mlxYYiQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_p60BkCQOEe-tg7y1lld14w" name="Constar de forma clara" outgoing="_rs31FyQOEe-tg7y1lld14w" incoming="_pPkFISQOEe-tg7y1lld14w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pPjeEiQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pPjeESQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pPjeEyQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pPjeFCQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pPjeFSQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pPjeFiQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pPjeGCQOEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pPjeFyQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_p60oqSQOEe-tg7y1lld14w">
            <targetForm xmi:type="expression:Expression" xmi:id="_Ib1J0S8FEe-lp6-MmZdV-w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_p60oqCQOEe-tg7y1lld14w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_p60oqyQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_sOFEsCQOEe-tg7y1lld14w" name="Gateway1" outgoing="_sz2EMCQOEe-tg7y1lld14w" incoming="_rs31FyQOEe-tg7y1lld14w _2K8WcCQOEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rs31ESQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rs31ECQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rs31EiQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_09uVYCQOEe-tg7y1lld14w" name="Regista a lead no CRM" outgoing="_JAZZgCQPEe-tg7y1lld14w" incoming="_sz2EMCQOEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sz1dIiQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sz1dISQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sz1dIyQOEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sz1dJCQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sz1dJSQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sz1dJiQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sz1dKCQOEe-tg7y1lld14w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sz1dJyQOEe-tg7y1lld14w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_JAYLYCQPEe-tg7y1lld14w" name="lead registada no CRM" incoming="_JAZZgCQPEe-tg7y1lld14w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JAYycSQPEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JAYycCQPEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JAYyciQPEe-tg7y1lld14w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ZSmSMCQOEe-tg7y1lld14w" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_4w734i78Ee-URJPyOm92Yg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ZSmSMiQOEe-tg7y1lld14w">
        <targetForm xmi:type="expression:Expression" xmi:id="_ZSmSMyQOEe-tg7y1lld14w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jInVCyQOEe-tg7y1lld14w" target="_kxxEICQOEe-tg7y1lld14w" source="_ghQRMCQOEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jIn8ECQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_jIn8ESQOEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mlxYZyQOEe-tg7y1lld14w" target="_m-rnoCQOEe-tg7y1lld14w" source="_kxxEICQOEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mlxYaCQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_mlxYaSQOEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pPkFISQOEe-tg7y1lld14w" name="sim" target="_p60BkCQOEe-tg7y1lld14w" source="_m-rnoCQOEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pPkFIiQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_pPkFIyQOEe-tg7y1lld14w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rs31FyQOEe-tg7y1lld14w" target="_sOFEsCQOEe-tg7y1lld14w" source="_p60BkCQOEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rs31GCQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_rs31GSQOEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sz2EMCQOEe-tg7y1lld14w" target="_09uVYCQOEe-tg7y1lld14w" source="_sOFEsCQOEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sz2EMSQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_sz2EMiQOEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2K8WcCQOEe-tg7y1lld14w" name="não" target="_sOFEsCQOEe-tg7y1lld14w" source="_m-rnoCQOEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2K8WcSQOEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_2K8WciQOEe-tg7y1lld14w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JAZZgCQPEe-tg7y1lld14w" target="_JAYLYCQPEe-tg7y1lld14w" source="_09uVYCQOEe-tg7y1lld14w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JAZZgSQPEe-tg7y1lld14w"/>
        <condition xmi:type="expression:Expression" xmi:id="_JAZZgiQPEe-tg7y1lld14w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_32FwACQWEe-tg7y1lld14w" name="Gestor de Oportunidade de Venda"/>
      <contract xmi:type="process:Contract" xmi:id="_ZSmSNCQOEe-tg7y1lld14w"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZSmSISQOEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_ZSmSIiQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZSmSIyQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZSmSJCQOEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_ZSmSJSQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZSmSJiQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZSmSJyQOEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_ZSmSKCQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZSmSKSQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZSmSKiQOEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_ZSmSKyQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZSmSLCQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ZSmSLSQOEe-tg7y1lld14w">
        <name xmi:type="expression:Expression" xmi:id="_ZSmSLiQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ZSmSLyQOEe-tg7y1lld14w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_asDfbBkUEe-yBLl2X56m4w" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_asDfbRkUEe-yBLl2X56m4w" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_asDfbhkUEe-yBLl2X56m4w" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_asDfbxkUEe-yBLl2X56m4w" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_asDfcBkUEe-yBLl2X56m4w" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_asDfcRkUEe-yBLl2X56m4w" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_asDfchkUEe-yBLl2X56m4w" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_asDfcxkUEe-yBLl2X56m4w" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_asDfdBkUEe-yBLl2X56m4w" name="Business_Object"/>
    <messageConnections xmi:type="process:MessageFlow" xmi:id="_plr1sC78Ee-URJPyOm92Yg" name="send_new_lead" target="_2mQBICQIEe-tg7y1lld14w" source="_cVc2EC75Ee-URJPyOm92Yg"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_asDfdRkUEe-yBLl2X56m4w" type="Process" element="_asDfQBkUEe-yBLl2X56m4w" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_-IiAcCQAEe-Mys7s4UWPsg" type="2007" element="_-AAWkCQAEe-Mys7s4UWPsg">
      <children xmi:type="notation:DecorationNode" xmi:id="_-IingCQAEe-Mys7s4UWPsg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_-IingSQAEe-Mys7s4UWPsg" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_YsvQMCQHEe-tg7y1lld14w" type="3002" element="_YstbACQHEe-tg7y1lld14w" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_YsvQMiQHEe-tg7y1lld14w" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_YsvQMyQHEe-tg7y1lld14w" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YsvQMSQHEe-tg7y1lld14w" x="90" y="69"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_e3Xs3CQPEe-tg7y1lld14w" type="3005" element="_e3XFwCQPEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_e3Xs3iQPEe-tg7y1lld14w" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e3Xs3SQPEe-tg7y1lld14w" x="210" y="36" width="182" height="90"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_cVddIy75Ee-URJPyOm92Yg" type="3011" element="_cVc2EC75Ee-URJPyOm92Yg" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_cVeEMC75Ee-URJPyOm92Yg" type="5028">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_cVeEMS75Ee-URJPyOm92Yg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cVddJC75Ee-URJPyOm92Yg" x="518" y="66" width="28" height="28"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_-IiAcSQAEe-Mys7s4UWPsg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_-IiAciQAEe-Mys7s4UWPsg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_-IiAcyQAEe-Mys7s4UWPsg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_-IingiQAEe-Mys7s4UWPsg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-IiAdCQAEe-Mys7s4UWPsg" width="621" height="220"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_asDfdhkUEe-yBLl2X56m4w" type="2007" element="_asDfQRkUEe-yBLl2X56m4w">
      <children xmi:type="notation:DecorationNode" xmi:id="_asDfdxkUEe-yBLl2X56m4w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_asDfeBkUEe-yBLl2X56m4w" type="7001">
        <children xmi:type="notation:Node" xmi:id="_asDfeRkUEe-yBLl2X56m4w" type="3007" element="_asDfQhkUEe-yBLl2X56m4w">
          <children xmi:type="notation:DecorationNode" xmi:id="_asDfehkUEe-yBLl2X56m4w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_asDfexkUEe-yBLl2X56m4w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_h6nEECP-Ee-Mys7s4UWPsg" type="3063" element="_h6iLkCP-Ee-Mys7s4UWPsg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_h6nrICP-Ee-Mys7s4UWPsg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h6nEESP-Ee-Mys7s4UWPsg" x="254" y="42" width="184" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2mRPQCQIEe-tg7y1lld14w" type="3012" element="_2mQBICQIEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_2mRPQiQIEe-tg7y1lld14w" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2mRPQyQIEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2mRPQSQIEe-tg7y1lld14w" x="115" y="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_asDfgxkUEe-yBLl2X56m4w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_asDfhBkUEe-yBLl2X56m4w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_asDfhRkUEe-yBLl2X56m4w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_asDfhhkUEe-yBLl2X56m4w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_asDfhxkUEe-yBLl2X56m4w" x="53" y="10" width="1292" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_UnHNsCP-Ee-Mys7s4UWPsg" type="3007" element="_Um81oCP-Ee-Mys7s4UWPsg">
          <children xmi:type="notation:DecorationNode" xmi:id="_UnIb0CP-Ee-Mys7s4UWPsg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_UnJC4CP-Ee-Mys7s4UWPsg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_rvF14CP-Ee-Mys7s4UWPsg" type="3008" element="_rvFO0CP-Ee-Mys7s4UWPsg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_rvGc8CP-Ee-Mys7s4UWPsg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rvGc8SP-Ee-Mys7s4UWPsg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rvF14SP-Ee-Mys7s4UWPsg" x="500" y="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_z8-dUCP-Ee-Mys7s4UWPsg" type="3063" element="_z89PMCP-Ee-Mys7s4UWPsg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_z8-dUiP-Ee-Mys7s4UWPsg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_z8-dUSP-Ee-Mys7s4UWPsg" x="716" y="63" width="172" height="86"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8znt4CP-Ee-Mys7s4UWPsg" type="3063" element="_8zmfwCP-Ee-Mys7s4UWPsg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8znt4iP-Ee-Mys7s4UWPsg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8znt4SP-Ee-Mys7s4UWPsg" x="716" y="200" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GUQWoCP_Ee-Mys7s4UWPsg" type="3063" element="_GUPIgCP_Ee-Mys7s4UWPsg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GUQWoiP_Ee-Mys7s4UWPsg" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GUQWoSP_Ee-Mys7s4UWPsg" x="980" y="195" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Tqh0MiP_Ee-Mys7s4UWPsg" type="3027" element="_TqhNICP_Ee-Mys7s4UWPsg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Tqh0NCP_Ee-Mys7s4UWPsg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Tqh0MyP_Ee-Mys7s4UWPsg" x="980" y="68" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VSXUuSP_Ee-Mys7s4UWPsg" type="3027" element="_VSXUsCP_Ee-Mys7s4UWPsg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VSX7wCP_Ee-Mys7s4UWPsg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VSXUuiP_Ee-Mys7s4UWPsg" x="1244" y="205" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bJrGUCP_Ee-Mys7s4UWPsg" type="3003" element="_bJqfQCP_Ee-Mys7s4UWPsg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_bJrGUiP_Ee-Mys7s4UWPsg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bJrGUyP_Ee-Mys7s4UWPsg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bJrGUSP_Ee-Mys7s4UWPsg" x="1508" y="224"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b2X0RCP_Ee-Mys7s4UWPsg" type="3003" element="_b2X0QCP_Ee-Mys7s4UWPsg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_b2X0RiP_Ee-Mys7s4UWPsg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_b2X0RyP_Ee-Mys7s4UWPsg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b2X0RSP_Ee-Mys7s4UWPsg" x="1508" y="87"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_UnH0wCP-Ee-Mys7s4UWPsg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_UnH0wSP-Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_UnH0wiP-Ee-Mys7s4UWPsg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_UnJC4SP-Ee-Mys7s4UWPsg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UnH0wyP-Ee-Mys7s4UWPsg" x="53" y="250" width="1292" height="400"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_asDfiBkUEe-yBLl2X56m4w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_asDfiRkUEe-yBLl2X56m4w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_asDfihkUEe-yBLl2X56m4w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_asDfixkUEe-yBLl2X56m4w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_asDfjBkUEe-yBLl2X56m4w" width="1698" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_DcEnkCQKEe-tg7y1lld14w" type="2007" element="_DTbo8CQKEe-tg7y1lld14w">
      <children xmi:type="notation:DecorationNode" xmi:id="_DcFOoCQKEe-tg7y1lld14w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_DcFOoSQKEe-tg7y1lld14w" type="7001">
        <children xmi:type="notation:Node" xmi:id="_LtkjsCQKEe-tg7y1lld14w" type="3007" element="_LtjVkCQKEe-tg7y1lld14w">
          <children xmi:type="notation:DecorationNode" xmi:id="_LtkjtSQKEe-tg7y1lld14w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_LtkjtiQKEe-tg7y1lld14w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_QG1C8CQKEe-tg7y1lld14w" type="3002" element="_QG0b4CQKEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QG1C8iQKEe-tg7y1lld14w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QG1C8yQKEe-tg7y1lld14w" x="29" y="15"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QG1C8SQKEe-tg7y1lld14w" x="127" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Y_H5XCQKEe-tg7y1lld14w" type="3005" element="_Y_HSQCQKEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Y_H5XiQKEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y_H5XSQKEe-tg7y1lld14w" x="326" y="80" width="184" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_cnYZcyQKEe-tg7y1lld14w" type="3008" element="_cnXyYCQKEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_cnYZdSQKEe-tg7y1lld14w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_cnYZdiQKEe-tg7y1lld14w" x="7" y="-89"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cnYZdCQKEe-tg7y1lld14w" x="667" y="102" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UwHQWCQMEe-tg7y1lld14w" type="3027" element="_UwGpQCQMEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UwH3YCQMEe-tg7y1lld14w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UwHQWSQMEe-tg7y1lld14w" x="851" y="77" width="195" height="98"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZoTuUCQMEe-tg7y1lld14w" type="3003" element="_ZoTHQCQMEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZoTuUiQMEe-tg7y1lld14w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZoTuUyQMEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZoTuUSQMEe-tg7y1lld14w" x="1841" y="111"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wdIJ8CQMEe-tg7y1lld14w" type="3008" element="_wdHi4CQMEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_wdIJ8iQMEe-tg7y1lld14w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_wdIJ8yQMEe-tg7y1lld14w" y="-74"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wdIJ8SQMEe-tg7y1lld14w" x="932" y="308" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mAxf3CQMEe-tg7y1lld14w" type="3005" element="_mAw4wCQMEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mAxf3iQMEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mAxf3SQMEe-tg7y1lld14w" x="1262" y="287" width="172" height="85"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7dk_oyQMEe-tg7y1lld14w" type="3003" element="_7dkYkCQMEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_7dk_pSQMEe-tg7y1lld14w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_7dk_piQMEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7dk_pCQMEe-tg7y1lld14w" x="1839" y="315"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_LtkjsSQKEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_LtkjsiQKEe-tg7y1lld14w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_LtkjsyQKEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_LtkjtyQKEe-tg7y1lld14w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LtkjtCQKEe-tg7y1lld14w" x="53" y="10" width="1982" height="428"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_ML_lECQKEe-tg7y1lld14w" type="3007" element="_ML-W8CQKEe-tg7y1lld14w">
          <children xmi:type="notation:DecorationNode" xmi:id="_ML_lFSQKEe-tg7y1lld14w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ML_lFiQKEe-tg7y1lld14w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_p-AKYCQMEe-tg7y1lld14w" type="3005" element="_p9_jUCQMEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_p-AKYiQMEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_p-AKYSQMEe-tg7y1lld14w" x="851" y="159" width="205" height="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0lXxtCQMEe-tg7y1lld14w" type="3008" element="_0lXxsCQMEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0lXxtiQMEe-tg7y1lld14w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0lXxtyQMEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0lXxtSQMEe-tg7y1lld14w" x="1334" y="180" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4DdpPCQMEe-tg7y1lld14w" type="3005" element="_4DdCICQMEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4DdpPiQMEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4DdpPSQMEe-tg7y1lld14w" x="1553" y="158" width="178" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5EC8dCQMEe-tg7y1lld14w" type="3003" element="_5EC8cCQMEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5EDjgCQMEe-tg7y1lld14w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5EDjgSQMEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5EC8dSQMEe-tg7y1lld14w" x="1838" y="192"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ML_lESQKEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ML_lEiQKEe-tg7y1lld14w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ML_lEyQKEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ML_lFyQKEe-tg7y1lld14w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ML_lFCQKEe-tg7y1lld14w" x="53" y="428" width="1982" height="360"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_DcEnkSQKEe-tg7y1lld14w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_DcEnkiQKEe-tg7y1lld14w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_DcEnkyQKEe-tg7y1lld14w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_DcFOoiQKEe-tg7y1lld14w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DcEnlCQKEe-tg7y1lld14w" width="2010" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_SUmasCQNEe-tg7y1lld14w" type="2007" element="_SUlzoCQNEe-tg7y1lld14w">
      <children xmi:type="notation:DecorationNode" xmi:id="_SUmatSQNEe-tg7y1lld14w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_SUmatiQNEe-tg7y1lld14w" type="7001">
        <children xmi:type="notation:Node" xmi:id="_eGmpISQNEe-tg7y1lld14w" type="3007" element="_eGmpICQNEe-tg7y1lld14w">
          <children xmi:type="notation:DecorationNode" xmi:id="_eGnQMCQNEe-tg7y1lld14w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eGnQMSQNEe-tg7y1lld14w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_hMvToSQNEe-tg7y1lld14w" type="3002" element="_hMuskCQNEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hMvToyQNEe-tg7y1lld14w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hMvTpCQNEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hMvToiQNEe-tg7y1lld14w" x="161" y="127"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_j7IMhSQNEe-tg7y1lld14w" type="3005" element="_j7HlcCQNEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_j7IMhyQNEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_j7IMhiQNEe-tg7y1lld14w" x="374" y="94" width="185" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_l8aHwyQNEe-tg7y1lld14w" type="3008" element="_l8ZgsCQNEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_l8aHxSQNEe-tg7y1lld14w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_l8aHxiQNEe-tg7y1lld14w" x="45" y="-72"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_l8aHxCQNEe-tg7y1lld14w" x="685" y="114" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wbWL3SQNEe-tg7y1lld14w" type="3005" element="_wbWL0CQNEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wbWy4CQNEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wbWL3iQNEe-tg7y1lld14w" x="782" y="262" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-iQcLCQNEe-tg7y1lld14w" type="3005" element="_-iP1ECQNEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-iQcLiQNEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-iQcLSQNEe-tg7y1lld14w" x="1406" y="258" width="149" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CH9XgyQOEe-tg7y1lld14w" type="3003" element="_CH8wcCQOEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_CH9XhSQOEe-tg7y1lld14w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_CH9XhiQOEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CH9XhCQOEe-tg7y1lld14w" x="1669" y="281"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HGPPbSQOEe-tg7y1lld14w" type="3005" element="_HGPPYCQOEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HGPPbyQOEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HGPPbiQOEe-tg7y1lld14w" x="1055" y="103" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JY4ncyQOEe-tg7y1lld14w" type="3003" element="_JY4AYCQOEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_JY4ndSQOEe-tg7y1lld14w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_JY4ndiQOEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JY4ndCQOEe-tg7y1lld14w" x="1669" y="121"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eGmpIiQNEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eGmpIyQNEe-tg7y1lld14w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eGmpJCQNEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eGnQMiQNEe-tg7y1lld14w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eGmpJSQNEe-tg7y1lld14w" x="53" y="10" width="1292" height="400"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_eRhfsCQNEe-tg7y1lld14w" type="3007" element="_eRg4oCQNEe-tg7y1lld14w">
          <children xmi:type="notation:DecorationNode" xmi:id="_eRhftSQNEe-tg7y1lld14w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_eRhftiQNEe-tg7y1lld14w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_1uMljCQNEe-tg7y1lld14w" type="3005" element="_1uL-cCQNEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1uMljiQNEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1uMljSQNEe-tg7y1lld14w" x="788" y="71" width="156" height="79"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5k6YbCQNEe-tg7y1lld14w" type="3005" element="_5k5xUCQNEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5k6YbiQNEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5k6YbSQNEe-tg7y1lld14w" x="1142" y="69" width="168" height="84"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_eRhfsSQNEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_eRhfsiQNEe-tg7y1lld14w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_eRhfsyQNEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_eRhftyQNEe-tg7y1lld14w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eRhftCQNEe-tg7y1lld14w" x="169" y="51"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_SUmasSQNEe-tg7y1lld14w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_SUmasiQNEe-tg7y1lld14w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_SUmasyQNEe-tg7y1lld14w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_SUmatyQNEe-tg7y1lld14w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SUmatCQNEe-tg7y1lld14w" width="1808" height="281"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_ZSm5MCQOEe-tg7y1lld14w" type="2007" element="_ZSmSICQOEe-tg7y1lld14w">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZSm5NSQOEe-tg7y1lld14w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ZSm5NiQOEe-tg7y1lld14w" type="7001">
        <children xmi:type="notation:Node" xmi:id="_bcYCECQOEe-tg7y1lld14w" type="3007" element="_bcXbACQOEe-tg7y1lld14w">
          <children xmi:type="notation:DecorationNode" xmi:id="_bcYCFSQOEe-tg7y1lld14w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_bcYCFiQOEe-tg7y1lld14w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ghQ4QCQOEe-tg7y1lld14w" type="3002" element="_ghQRMCQOEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ghQ4QiQOEe-tg7y1lld14w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ghQ4QyQOEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ghQ4QSQOEe-tg7y1lld14w" x="144" y="128"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kxxELSQOEe-tg7y1lld14w" type="3005" element="_kxxEICQOEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_kxxELyQOEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kxxELiQOEe-tg7y1lld14w" x="350" y="103" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_m-rnpCQOEe-tg7y1lld14w" type="3008" element="_m-rnoCQOEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_m-rnpiQOEe-tg7y1lld14w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_m-rnpyQOEe-tg7y1lld14w" y="-70"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m-rnpSQOEe-tg7y1lld14w" x="651" y="121" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_p60orCQOEe-tg7y1lld14w" type="3005" element="_p60BkCQOEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_p60oriQOEe-tg7y1lld14w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_p60orSQOEe-tg7y1lld14w" x="826" y="104" width="155" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sOFrwCQOEe-tg7y1lld14w" type="3008" element="_sOFEsCQOEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sOFrwiQOEe-tg7y1lld14w" visible="false" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sOFrwyQOEe-tg7y1lld14w" x="1" y="-67"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sOFrwSQOEe-tg7y1lld14w" x="1119" y="118" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_09vjgCQOEe-tg7y1lld14w" type="3027" element="_09uVYCQOEe-tg7y1lld14w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_09vjgiQOEe-tg7y1lld14w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_09vjgSQOEe-tg7y1lld14w" x="1310" y="96" width="147" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JAYycyQPEe-tg7y1lld14w" type="3003" element="_JAYLYCQPEe-tg7y1lld14w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_JAYydSQPEe-tg7y1lld14w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_JAYydiQPEe-tg7y1lld14w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JAYydCQPEe-tg7y1lld14w" x="1598" y="125"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_bcYCESQOEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_bcYCEiQOEe-tg7y1lld14w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_bcYCEyQOEe-tg7y1lld14w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_bcYCFyQOEe-tg7y1lld14w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bcYCFCQOEe-tg7y1lld14w" x="53" y="10" width="1540" height="336"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_ZSm5MSQOEe-tg7y1lld14w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZSm5MiQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_ZSm5MyQOEe-tg7y1lld14w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ZSm5NyQOEe-tg7y1lld14w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZSm5NCQOEe-tg7y1lld14w" width="1751" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_asDfjRkUEe-yBLl2X56m4w"/>
    <edges xmi:type="notation:Connector" xmi:id="_vXFQQSP-Ee-Mys7s4UWPsg" type="4001" element="_vXEpMCP-Ee-Mys7s4UWPsg" source="_h6nEECP-Ee-Mys7s4UWPsg" target="_rvF14CP-Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vXF3UCP-Ee-Mys7s4UWPsg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vXF3USP-Ee-Mys7s4UWPsg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vXFQQiP-Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vXFQQyP-Ee-Mys7s4UWPsg" points="[0, 0, -101, -286]$[104, 0, 3, -286]$[104, 267, 3, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vXHFcCP-Ee-Mys7s4UWPsg" id="(0.9891304347826086,0.8043478260869565)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_w2fNgCP-Ee-Mys7s4UWPsg" id="(0.46511627906976744,0.09302325581395349)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_24QisCP-Ee-Mys7s4UWPsg" type="4001" element="_24OGcCP-Ee-Mys7s4UWPsg" source="_rvF14CP-Ee-Mys7s4UWPsg" target="_z8-dUCP-Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_24RJwCP-Ee-Mys7s4UWPsg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_24RJwSP-Ee-Mys7s4UWPsg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_24QisSP-Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_24QisiP-Ee-Mys7s4UWPsg" points="[-1, -6, -257, 0]$[245, -7, -11, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_24S-8CP-Ee-Mys7s4UWPsg" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_24S-8SP-Ee-Mys7s4UWPsg" id="(0.06395348837209303,0.45348837209302323)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AgavwCP_Ee-Mys7s4UWPsg" type="4001" element="_AgQ-wCP_Ee-Mys7s4UWPsg" source="_rvF14CP-Ee-Mys7s4UWPsg" target="_8znt4CP-Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AgbW0CP_Ee-Mys7s4UWPsg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AgbW0SP_Ee-Mys7s4UWPsg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AgavwSP_Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AgavwiP_Ee-Mys7s4UWPsg" points="[-22, 11, -207, -136]$[-22, 137, -207, -10]$[173, 137, -12, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Agck8CP_Ee-Mys7s4UWPsg" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Agck8SP_Ee-Mys7s4UWPsg" id="(0.0625,0.6145833333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JqvxUyP_Ee-Mys7s4UWPsg" type="4001" element="_JqvxUCP_Ee-Mys7s4UWPsg" source="_8znt4CP-Ee-Mys7s4UWPsg" target="_GUQWoCP_Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JqwYYCP_Ee-Mys7s4UWPsg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JqwYYSP_Ee-Mys7s4UWPsg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JqvxVCP_Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JqvxVSP_Ee-Mys7s4UWPsg" points="[0, 8, -105, -4]$[72, 8, -33, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JqxmgCP_Ee-Mys7s4UWPsg" id="(1.0,0.36904761904761907)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JqxmgSP_Ee-Mys7s4UWPsg" id="(0.1896551724137931,0.5172413793103449)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RgQVACP_Ee-Mys7s4UWPsg" type="4001" element="_RgPt8CP_Ee-Mys7s4UWPsg" source="_z8-dUCP-Ee-Mys7s4UWPsg" target="_Tqh0MiP_Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RgQVAyP_Ee-Mys7s4UWPsg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RgQVBCP_Ee-Mys7s4UWPsg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RgQVASP_Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RgQVAiP_Ee-Mys7s4UWPsg" points="[0, 10, -102, -3]$[80, 10, -22, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RgRjICP_Ee-Mys7s4UWPsg" id="(1.0,0.36046511627906974)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RgRjISP_Ee-Mys7s4UWPsg" id="(0.14666666666666667,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VSX7xCP_Ee-Mys7s4UWPsg" type="4001" element="_VSX7wSP_Ee-Mys7s4UWPsg" source="_GUQWoCP_Ee-Mys7s4UWPsg" target="_VSXUuSP_Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VSYi0CP_Ee-Mys7s4UWPsg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VSYi0SP_Ee-Mys7s4UWPsg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VSX7xSP_Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VSX7xiP_Ee-Mys7s4UWPsg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bJrGVyP_Ee-Mys7s4UWPsg" type="4001" element="_bJrGVCP_Ee-Mys7s4UWPsg" source="_VSXUuSP_Ee-Mys7s4UWPsg" target="_bJrGUCP_Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bJrtYCP_Ee-Mys7s4UWPsg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bJrtYSP_Ee-Mys7s4UWPsg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bJrGWCP_Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bJrGWSP_Ee-Mys7s4UWPsg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_b2YbUyP_Ee-Mys7s4UWPsg" type="4001" element="_b2YbUCP_Ee-Mys7s4UWPsg" source="_Tqh0MiP_Ee-Mys7s4UWPsg" target="_b2X0RCP_Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_b2YbViP_Ee-Mys7s4UWPsg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_b2YbVyP_Ee-Mys7s4UWPsg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_b2YbVCP_Ee-Mys7s4UWPsg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_b2YbVSP_Ee-Mys7s4UWPsg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r_hvgCQHEe-tg7y1lld14w" type="4001" element="_r_hIcCQHEe-tg7y1lld14w" source="_YsvQMCQHEe-tg7y1lld14w" target="_e3Xs3CQPEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r_hvgyQHEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r_hvhCQHEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r_hvgSQHEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r_hvgiQHEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1R1y8yQIEe-tg7y1lld14w" type="4001" element="_1R1y8CQIEe-tg7y1lld14w" source="_e3Xs3CQPEe-tg7y1lld14w" target="_cVddIy75Ee-URJPyOm92Yg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1R2aACQIEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1R2aASQIEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1R1y9CQIEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1R1y9SQIEe-tg7y1lld14w" points="[0, 15, -140, -2]$[126, 15, -14, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1R3oICQIEe-tg7y1lld14w" id="(1.0,0.3076923076923077)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r_3b0CQJEe-tg7y1lld14w" type="4001" element="_r_20wCQJEe-tg7y1lld14w" source="_2mRPQCQIEe-tg7y1lld14w" target="_h6nEECP-Ee-Mys7s4UWPsg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r_3b0yQJEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r_3b1CQJEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r_3b0SQJEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r_3b0iQJEe-tg7y1lld14w" points="[-1, -16, -106, 7]$[91, -25, -14, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r_4p8CQJEe-tg7y1lld14w" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r_4p8SQJEe-tg7y1lld14w" id="(0.07608695652173914,0.40217391304347827)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YioKliQKEe-tg7y1lld14w" type="4001" element="_YioKkyQKEe-tg7y1lld14w" source="_QG1C8CQKEe-tg7y1lld14w" target="_Y_H5XCQKEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YioxoCQKEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YioxoSQKEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YioKlyQKEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YioKmCQKEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_b-kF-SQKEe-tg7y1lld14w" type="4001" element="_b-kF9iQKEe-tg7y1lld14w" source="_Y_H5XCQKEe-tg7y1lld14w" target="_cnYZcyQKEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_b-ktACQKEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_b-ktASQKEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_b-kF-iQKEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_b-kF-yQKEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UwH3ZCQMEe-tg7y1lld14w" type="4001" element="_UwH3YSQMEe-tg7y1lld14w" source="_cnYZcyQKEe-tg7y1lld14w" target="_UwHQWCQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UwIecCQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UwIecSQMEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UwH3ZSQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UwH3ZiQMEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZoTuVyQMEe-tg7y1lld14w" type="4001" element="_ZoTuVCQMEe-tg7y1lld14w" source="_UwHQWCQMEe-tg7y1lld14w" target="_ZoTuUCQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZoUVYCQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZoUVYSQMEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZoTuWCQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZoTuWSQMEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dNRC1SQMEe-tg7y1lld14w" type="4001" element="_dNRC0iQMEe-tg7y1lld14w" source="_cnYZcyQKEe-tg7y1lld14w" target="_wdIJ8CQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dNRC2CQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dNRC2SQMEe-tg7y1lld14w" x="10" y="-146"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dNRC1iQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dNRC1yQMEe-tg7y1lld14w" points="[6, 16, -259, -190]$[6, 205, -259, -1]$[245, 205, -20, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ih0FpiQMEe-tg7y1lld14w" type="4001" element="_ih0FoyQMEe-tg7y1lld14w" source="_wdIJ8CQMEe-tg7y1lld14w" target="_mAxf3CQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ih0ssCQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ih0ssSQMEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ih0FpyQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ih0FqCQMEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_m3az8yQMEe-tg7y1lld14w" type="4001" element="_m3az8CQMEe-tg7y1lld14w" source="_wdIJ8CQMEe-tg7y1lld14w" target="_p-AKYCQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_m3az9iQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_m3az9yQMEe-tg7y1lld14w" x="-20" y="-16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_m3az9CQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_m3az9SQMEe-tg7y1lld14w" points="[0, 22, -5, -183]$[0, 154, -5, -51]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sW8-wyQMEe-tg7y1lld14w" type="4001" element="_sW8-wCQMEe-tg7y1lld14w" source="_p-AKYCQMEe-tg7y1lld14w" target="_0lXxtCQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sW8-xiQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sW8-xyQMEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sW8-xCQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sW8-xSQMEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uTPsUyQMEe-tg7y1lld14w" type="4001" element="_uTPsUCQMEe-tg7y1lld14w" source="_0lXxtCQMEe-tg7y1lld14w" target="_mAxf3CQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uTQTYCQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uTQTYSQMEe-tg7y1lld14w" x="-7" y="-33"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uTPsVCQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uTPsVSQMEe-tg7y1lld14w" points="[-1, -4, 38, 253]$[-73, -203, -34, 54]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uTQ6cCQMEe-tg7y1lld14w" id="(1.0,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2SVp0yQMEe-tg7y1lld14w" type="4001" element="_2SVp0CQMEe-tg7y1lld14w" source="_0lXxtCQMEe-tg7y1lld14w" target="_4DdpPCQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2SVp1iQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2SVp1yQMEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2SVp1CQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2SVp1SQMEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5EDjhSQMEe-tg7y1lld14w" type="4001" element="_5EDjgiQMEe-tg7y1lld14w" source="_4DdpPCQMEe-tg7y1lld14w" target="_5EC8dCQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5EDjiCQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5EDjiSQMEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5EDjhiQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5EDjhyQMEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7dlmsiQMEe-tg7y1lld14w" type="4001" element="_7dk_pyQMEe-tg7y1lld14w" source="_mAxf3CQMEe-tg7y1lld14w" target="_7dk_oyQMEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7dlmtSQMEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7dlmtiQMEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7dlmsyQMEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7dlmtCQMEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jUpbUiQNEe-tg7y1lld14w" type="4001" element="_jUo0SyQNEe-tg7y1lld14w" source="_hMvToSQNEe-tg7y1lld14w" target="_j7IMhSQNEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jUpbVSQNEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jUpbViQNEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jUpbUyQNEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jUpbVCQNEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lcB-kCQNEe-tg7y1lld14w" type="4001" element="_lcBXhyQNEe-tg7y1lld14w" source="_j7IMhSQNEe-tg7y1lld14w" target="_l8aHwyQNEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lcB-kyQNEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lcB-lCQNEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lcB-kSQNEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lcB-kiQNEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uo3hkiQNEe-tg7y1lld14w" type="4001" element="_uo26gyQNEe-tg7y1lld14w" source="_l8aHwyQNEe-tg7y1lld14w" target="_wbWL3SQNEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uo3hlSQNEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uo3hliQNEe-tg7y1lld14w" x="-47" y="-16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uo3hkyQNEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uo3hlCQNEe-tg7y1lld14w" points="[0, 22, -160, -147]$[0, 175, -160, 6]$[76, 175, -84, 6]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zay_gyQNEe-tg7y1lld14w" type="4001" element="_zay_gCQNEe-tg7y1lld14w" source="_wbWL3SQNEe-tg7y1lld14w" target="_1uMljCQNEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zay_hiQNEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zay_hyQNEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zay_hCQNEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zay_hSQNEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_21PGHiQNEe-tg7y1lld14w" type="4001" element="_21PGGyQNEe-tg7y1lld14w" source="_1uMljCQNEe-tg7y1lld14w" target="_5k6YbCQNEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_21PGISQNEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_21PGIiQNEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_21PGHyQNEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_21PGICQNEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7BH3tCQNEe-tg7y1lld14w" type="4001" element="_7BH3sSQNEe-tg7y1lld14w" source="_5k6YbCQNEe-tg7y1lld14w" target="_-iQcLCQNEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7BH3tyQNEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7BH3uCQNEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7BH3tSQNEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7BH3tiQNEe-tg7y1lld14w" points="[84, -1, -170, 215]$[132, -1, -122, 215]$[132, -216, -122, 0]$[180, -216, -74, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CH9-kCQOEe-tg7y1lld14w" type="4001" element="_CH9XhyQOEe-tg7y1lld14w" source="_-iQcLCQNEe-tg7y1lld14w" target="_CH9XgyQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CH9-kyQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CH9-lCQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CH9-kSQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CH9-kiQOEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EbeSQiQOEe-tg7y1lld14w" type="4001" element="_EbdrPCQOEe-tg7y1lld14w" source="_l8aHwyQNEe-tg7y1lld14w" target="_HGPPbSQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EbeSRSQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EbeSRiQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EbeSQyQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EbeSRCQOEe-tg7y1lld14w" points="[22, 0, -400, -4]$[349, 0, -73, -4]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JY4neiQOEe-tg7y1lld14w" type="4001" element="_JY4ndyQOEe-tg7y1lld14w" source="_HGPPbSQOEe-tg7y1lld14w" target="_JY4ncyQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JY5OgCQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JY5OgSQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JY4neyQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JY4nfCQOEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jIn8EiQOEe-tg7y1lld14w" type="4001" element="_jInVCyQOEe-tg7y1lld14w" source="_ghQ4QCQOEe-tg7y1lld14w" target="_kxxELSQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jIn8FSQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jIn8FiQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jIn8EyQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jIn8FCQOEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mlx_cCQOEe-tg7y1lld14w" type="4001" element="_mlxYZyQOEe-tg7y1lld14w" source="_kxxELSQOEe-tg7y1lld14w" target="_m-rnpCQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mlx_cyQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mlx_dCQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mlx_cSQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mlx_ciQOEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pPkFJCQOEe-tg7y1lld14w" type="4001" element="_pPkFISQOEe-tg7y1lld14w" source="_m-rnpCQOEe-tg7y1lld14w" target="_p60orCQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pPkFJyQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pPkFKCQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pPkFJSQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pPkFJiQOEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rs31GiQOEe-tg7y1lld14w" type="4001" element="_rs31FyQOEe-tg7y1lld14w" source="_p60orCQOEe-tg7y1lld14w" target="_sOFrwCQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rs31HSQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rs31HiQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rs31GyQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rs31HCQOEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sz2EMyQOEe-tg7y1lld14w" type="4001" element="_sz2EMCQOEe-tg7y1lld14w" source="_sOFrwCQOEe-tg7y1lld14w" target="_09vjgCQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sz2ENiQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sz2ENyQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sz2ENCQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sz2ENSQOEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2K_ZwCQOEe-tg7y1lld14w" type="4001" element="_2K8WcCQOEe-tg7y1lld14w" source="_m-rnpCQOEe-tg7y1lld14w" target="_sOFrwCQOEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2K_ZwyQOEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2K_ZxCQOEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2K_ZwSQOEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2K_ZwiQOEe-tg7y1lld14w" points="[-22, 16, -468, 25]$[-22, 92, -468, 101]$[446, 92, 0, 101]$[446, 13, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2LAA0CQOEe-tg7y1lld14w" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JAZZgyQPEe-tg7y1lld14w" type="4001" element="_JAZZgCQPEe-tg7y1lld14w" source="_09vjgCQOEe-tg7y1lld14w" target="_JAYycyQPEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JAZZhiQPEe-tg7y1lld14w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JAZZhyQPEe-tg7y1lld14w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JAZZhCQPEe-tg7y1lld14w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JAZZhSQPEe-tg7y1lld14w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_plscwC78Ee-URJPyOm92Yg" type="4002" element="_plr1sC78Ee-URJPyOm92Yg" source="_cVddIy75Ee-URJPyOm92Yg" target="_2mRPQCQIEe-tg7y1lld14w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_plscwy78Ee-URJPyOm92Yg" type="6003">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_plscxC78Ee-URJPyOm92Yg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_plscwS78Ee-URJPyOm92Yg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_plscwi78Ee-URJPyOm92Yg" points="[0, 13, 374, -232]$[0, 106, 374, -139]$[-370, 106, 4, -139]$[-370, 230, 4, -15]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
